### ISSUE TITLE
[Feat] 좋아요

### ISSUE THREAD

**Issue by GaEun1216** [HeartVera/HeartVera#22]
**🌟 Issue : Feature**
좋아요 기능 구현

**Description**
좋아요 엔티티 작성 및 기능 적용

**Todo**
작업해야 하는 투두리스트를 작성해주세요.

- [x] 좋아요 Entity, Dto, Repository 작성
- [x] 좋아요 Controller, service 작성
- [x] 좋아요 수 조회
- [ ] 게시글 좋아요 수 업데이트 (추가/삭제) 토글 형태로 구현 예정
- [ ] 댓글 좋아요 수 업데이트 (추가/삭제) 토글 형태로 구현 예정

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
![image](https://github.com/HeartVera/HeartVera/assets/51986588/8f6e3bd4-36e0-446a-bfa4-46e11dd452e2)
