### ISSUE TITLE
[Refactor] Swagger 태그 설정 / 예외처리

### ISSUE THREAD

**Issue by GaEun1216** [HeartVera/HeartVera#28]
**🌟 Issue : Feature**
필수 구현 기능의 Swagger tag 달기
글로벌 예외 처리하기

**Description**
auth / user / post / comment 를 중점으로 리팩토링 예정입니다.

**Todo**
- [x] swagger 태그 및 설명 달기
- [x] 예외처리 확인하기
- [x] post 함수명 수정
- [x] comment에서 postService 접근하도록 수정
- [x] signup 함수 관심사 분리로 가독성 높이기
- [x] refreshtoken @Data 사용 지양하기
