### ISSUE TITLE
[Feat] UserService 단위테스트

### ISSUE THREAD

**Issue by HaejungHan** [HeartVera/HeartVera#34]
**🌟 Issue : Feature**
UserService 단위테스트 작성

**Description**
- 프로필조회, 프로필 수정, 비밀번호 변경 성공
- (실패케이스) 현재 비밀번호 불일치, 변경하려는 비밀번화 동일한 비밀번호일 경우, 변경하려는 비밀번호와 최근사용한 비밀번호 동일한 경우

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 테스트유저 객체 필요
- [ ] 프로필조회, 프로필 수정, 비밀번호 변경 성공 케이스
- [ ] (실패케이스) 현재 비밀번호 불일치, 변경하려는 비밀번화 동일한 비밀번호일 경우, 변경하려는 비밀번호와 최근사용한 비밀번호 동일한 경우
